// Code generated by iam-codegen from iam-permission-manifest.json. DO NOT EDIT.
package sharedpermissions

import "github.com/axis-iam/vertex-sdk-go/authz"

var OrdersRead = authz.PermissionKey{Resource: "orders", Action: "read"}

var All = []authz.PermissionDefinition{
	{Resource: "orders", Action: "read", Description: "Read orders"},
}
