// Package generator renders Go source files for declared IAM permission
// definitions and parses existing permission.go sources.
package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"text/template"
	"unicode"
	"unicode/utf8"

	"github.com/axis-iam/vertex-sdk-go/authz"
	"golang.org/x/text/unicode/norm"
)

// Input drives the template.
type Input struct {
	Package     string
	GoImport    string // defaults to "github.com/axis-iam/vertex-sdk-go/authz"
	Permissions []authz.PermissionDefinition
}

// Render produces the Go source for permissions.gen.go.
func Render(in Input) ([]byte, error) {
	if in.Package == "" {
		return nil, fmt.Errorf("generator: empty package name")
	}
	if in.GoImport == "" {
		in.GoImport = "github.com/axis-iam/vertex-sdk-go/authz"
	}
	sorted := append([]authz.PermissionDefinition(nil), in.Permissions...)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].Resource != sorted[j].Resource {
			return sorted[i].Resource < sorted[j].Resource
		}
		return sorted[i].Action < sorted[j].Action
	})

	type entry struct {
		ConstName   string
		Resource    string
		Action      string
		Description string
	}
	rendered := make([]entry, len(sorted))
	names := make(map[string]string, len(sorted))
	keys := make(map[string]struct{}, len(sorted))
	for i, d := range sorted {
		wireKey := d.Resource + ":" + d.Action
		if !d.Key().IsConcrete() {
			return nil, fmt.Errorf("generator: invalid concrete permission key: %s", wireKey)
		}
		if !utf8.ValidString(d.Description) || !norm.NFC.IsNormalString(d.Description) {
			return nil, fmt.Errorf("generator: permission description must already be NFC: %s", wireKey)
		}
		if _, exists := keys[wireKey]; exists {
			return nil, fmt.Errorf("generator: duplicate permission key: %s", wireKey)
		}
		keys[wireKey] = struct{}{}
		constName := ConstName(d.Resource, d.Action)
		if previous, exists := names[constName]; exists {
			return nil, fmt.Errorf("generator: generated permission name collision: %s and %s both map to %s", previous, wireKey, constName)
		}
		names[constName] = wireKey
		rendered[i] = entry{
			ConstName:   constName,
			Resource:    d.Resource,
			Action:      d.Action,
			Description: d.Description,
		}
	}

	tpl := template.Must(template.New("perms").Parse(fileTemplate))
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, map[string]any{
		"Package": in.Package,
		"Import":  in.GoImport,
		"Entries": rendered,
	}); err != nil {
		return nil, err
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("generator: gofmt: %w (source below)\n%s", err, buf.String())
	}
	return formatted, nil
}

// ConstName turns a resource+action pair into a valid Go identifier.
// "signing-keys" + "read" becomes "SigningKeysRead". Callers must pass
// concrete manifest keys; Render rejects wildcard declarations before naming.
func ConstName(resource, action string) string {
	name := pascal(resource) + pascal(action)
	if name == "" {
		return "Permission"
	}
	if name != "" && name[0] >= '0' && name[0] <= '9' {
		return "P" + name
	}
	return name
}

func pascal(s string) string {
	if s == "*" {
		return "Wildcard"
	}
	var b strings.Builder
	upper := true
	for _, r := range s {
		switch {
		case r == '-' || r == '_' || r == '.' || r == ' ' || r == '/':
			upper = true
		case upper:
			b.WriteRune(unicode.ToUpper(r))
			upper = false
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

const fileTemplate = `// Code generated by iam-codegen. DO NOT EDIT.
package {{.Package}}

import "{{.Import}}"

var (
{{- range .Entries}}
	{{.ConstName}} = authz.PermissionKey{Resource: {{printf "%q" .Resource}}, Action: {{printf "%q" .Action}}}
{{- end}}
)

// All is the concrete list used by request-time authorization helpers.
var All = []authz.PermissionDefinition{
{{- range .Entries}}
	{Resource: {{printf "%q" .Resource}}, Action: {{printf "%q" .Action}}, Description: {{printf "%q" .Description}}},
{{- end}}
}
`
